version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    environment:
      COGNITO_USER_POOL_ID: <seu_user_pool_id>
      COGNITO_CLIENT_ID: <seu_client_id>
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhafacil123
      POSTGRES_DB: ProjNode
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhafacil123
      POSTGRES_DB: ProjNode
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: